# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Juanito', max_length=66)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('semestre', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
